apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: user-serviceee
  
  labels:
    app: user-service
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      #imagePullSecrets:
      #- name: bodyshop-dev
      containers:
      - name: user-service
        image: 718140854052.dkr.ecr.ap-south-1.amazonaws.com/dev-user-poc:api-user-300
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: user-service
        - containerPort: 4001
          name: user-grpc
        resources:
          limits:
            cpu: "150m"
            memory: "250Mi"
          requests:
            cpu: "150m"
            memory: "250Mi"
