apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: backend-svc
  labels:
    app: backend-svc
  namespace: uatenv
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend-svc
  template:
    metadata:
      labels:
        app: backend-svc
    spec:
      containers:
      - name: backend-svc
        image: argoproj/rollouts-demo:green
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "151m"
            memory: "250Mi"
          requests:
            cpu: "150m"
            memory: "250Mi"
