apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    app: backend-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: backend-svc
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
